### ISSUE TITLE
UUID on DB is truncated on the way

### ISSUE THREAD

**Issue by tsasaki609** [odo-network/sequelize-binary-uuid#2]
Hi,

After running this sample code, it appeared that the UUID was generated correctly on the log.
https://github.com/odo-network/sequelize-binary-uuid#using-withbinaryuuid-preset-recommended

However, when referring to a table on MySQL, it seems that UUID is set as truncation on the way.

Records on Users:
> mysql> select * from Users;
> +------------------+---------+---------------------+---------------------+
> | id               | someKey | createdAt           | updatedAt           |
> +------------------+---------+---------------------+---------------------+
> | X'11e9ecae67bcec | one     | 2019-10-12 05:09:02 | 2019-10-12 05:09:02 |
> | X'11e9ecae67bd88 | two     | 2019-10-12 05:09:02 | 2019-10-12 05:09:02 |
> | X'11e9ecae67bdaf | three   | 2019-10-12 05:09:02 | 2019-10-12 05:09:02 |
> +------------------+---------+---------------------+---------------------+
> 3 rows in set (0.00 sec)
> mysql> select cast(id as char(1000)) from Users;
> +------------------------+
> | cast(id as char(1000)) |
> +------------------------+
> | X'11e9ecae67bcec       |
> | X'11e9ecae67bd88       |
> | X'11e9ecae67bdaf       |
> +------------------------+
> 3 rows in set (0.01 sec)

MySQL Query Log:
> 2019-10-12T05:09:01.950921Z	   37 Query	DROP TABLE IF EXISTS `Users`
> 2019-10-12T05:09:01.959407Z	   37 Query	CREATE TABLE IF NOT EXISTS `Users` (`id` BINARY(16) , `someKey` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
> 2019-10-12T05:09:02.057988Z	   37 Prepare	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES (?,?,?,?)
> 2019-10-12T05:09:02.059023Z	   37 Execute	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES ('X\'11e9ecae67bcec908aa3bd16bb450b69\'','one','2019-10-12 05:09:02','2019-10-12 05:09:02')
> 2019-10-12T05:09:02.061425Z	   38 Prepare	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES (?,?,?,?)
> 2019-10-12T05:09:02.062524Z	   39 Prepare	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES (?,?,?,?)
> 2019-10-12T05:09:02.062919Z	   38 Execute	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES ('X\'11e9ecae67bd88d08aa3bd16bb450b69\'','two','2019-10-12 05:09:02','2019-10-12 05:09:02')
> 2019-10-12T05:09:02.063169Z	   39 Execute	INSERT INTO `Users` (`id`,`someKey`,`createdAt`,`updatedAt`) VALUES ('X\'11e9ecae67bdafe08aa3bd16bb450b69\'','three','2019-10-12 05:09:02','2019-10-12 05:09:02')
> 2019-10-12T05:09:02.069641Z	   39 Query	SELECT `id`, `someKey`, `createdAt`, `updatedAt` FROM `Users` AS `User`

**Comment by tsasaki609** [comment]
# Test Environment
## MySQL
8.0.17

## Node dependencies
mysql2: 1.7.0
sequelize: 5.19.5

**Comment by sgeb** [comment]
See https://github.com/odo-network/sequelize-binary-uuid/pull/3#issuecomment-599056408 for a package containing this fix.
